/*
Autogenerated by excavator tool, version 1.0.0.0
__GENERATED_TIMESTAMP__
Source: 129.212.168.210,1433
Database: budzdorov_Core
*/
use budzdorov_Core


GO
set nocount on
go
set ansi_nulls on
go
set quoted_identifier on
go

begin try
begin tran
	--#region [dbo].[SchemaTestChild]
		declare @SchemaTestParentUnIdUn1 int
				if not exists(select * from [audit].[SchemaTestParent] where [Id] = 1 )
			begin
				select @SchemaTestParentUnIdUn1 = max(Id)+1 from [audit].[SchemaTestParent]
				select @SchemaTestParentUnIdUn1 = isnull(@SchemaTestParentUnIdUn1, 1)

				insert into [audit].[SchemaTestParent] ([Id],[Note])
		values (@SchemaTestParentUnIdUn1,N'cross-schema test root')
			end
			else
			begin
				update [audit].[SchemaTestParent]
				set [Note] = N'cross-schema test root'
				where [Id] = @SchemaTestParentUnIdUn1

				select @SchemaTestParentUnIdUn1 = Id
				from [audit].[SchemaTestParent]
				where [Id] = @SchemaTestParentUnIdUn1

			end
		declare @SchemaTestChildUnIdUn100 int

		if not exists(select * from [dbo].[SchemaTestChild] where [Id] = 100 )
		begin
		select @SchemaTestChildUnIdUn100 = max(Id)+1 from [dbo].[SchemaTestChild]
		select @SchemaTestChildUnIdUn100 = isnull(@SchemaTestChildUnIdUn100, 1)

		insert into [dbo].[SchemaTestChild] ([Id],[ParentId])
		values (@SchemaTestChildUnIdUn100,@SchemaTestParentUnIdUn1)

		end
	else
		begin
			update [dbo].[SchemaTestChild]
			set [ParentId] = @SchemaTestParentUnIdUn1
			where [Id] = @SchemaTestChildUnIdUn100
			select @SchemaTestChildUnIdUn100 = Id
			from [dbo].[SchemaTestChild]
			where [Id] = @SchemaTestChildUnIdUn100
		end

	--#endregion [dbo].[SchemaTestChild]

rollback

end try
--#region catch
begin catch
	declare @Err_msg nvarchar(2048), @Err_svrt int
	select @Err_msg = isnull(error_message(), 'has not been retrieved'), @Err_svrt = error_severity();
	if @@trancount > 0 rollback;
	raiserror (@Err_msg, @Err_svrt, 1) with nowait;
end catch;

--#endregion
