/*
Autogenerated by excavator tool, version 1.0.0.0
__GENERATED_TIMESTAMP__
Source: 129.212.168.210,1433
Database: budzdorov_Core
*/
use budzdorov_Core


GO
set nocount on
go
set ansi_nulls on
go
set quoted_identifier on
go

begin try
begin tran
	--#region TherapyProgramItems
		declare @TherapyProgramItemsUnIdUn1039 int

		if not exists(select * from TherapyProgramItems where [Id] = 1039 )
		begin
		insert into TherapyProgramItems ([MedicalService_Id],[IsCanceled],[DiscountValue],[DiscountPercent],[DiscountedPrice],[ServicesCount],[ProvidedServicesCount],[Program_Id],[ServicesCanBeCancelled],[ServicesCanBeAdded],[PaymentMethod],[AllServicesCost_Price],[AllServicesCost_DiscountPercents],[AllServicesCost_DiscountValue],[AllProvidedServicesCost_Price],[AllProvidedServicesCost_DiscountPercents],[AllProvidedServicesCost_DiscountValue])
		values (6793,0,0.0000,0,1690.0000,1,1,904,1,1,0,1690.0000,0,0.0000,1690.0000,0,0.0000)
		set @TherapyProgramItemsUnIdUn1039 = SCOPE_IDENTITY()

		end
	else
		begin
			update TherapyProgramItems
			set [MedicalService_Id] = 6793 , [IsCanceled] = 0 , [DiscountValue] = 0.0000 , [DiscountPercent] = 0 , [DiscountedPrice] = 1690.0000 , [ServicesCount] = 1 , [ProvidedServicesCount] = 1 , [Program_Id] = 904 , [ServicesCanBeCancelled] = 1 , [ServicesCanBeAdded] = 1 , [PaymentMethod] = 0 , [AllServicesCost_Price] = 1690.0000 , [AllServicesCost_DiscountPercents] = 0 , [AllServicesCost_DiscountValue] = 0.0000 , [AllProvidedServicesCost_Price] = 1690.0000 , [AllProvidedServicesCost_DiscountPercents] = 0 , [AllProvidedServicesCost_DiscountValue] = 0.0000
			where [Id] = 1039
			select @TherapyProgramItemsUnIdUn1039 = Id
			from TherapyProgramItems
			where [Id] = 1039
		end

	--#endregion TherapyProgramItems

rollback

end try
--#region catch
begin catch
	declare @Err_msg nvarchar(2048), @Err_svrt int
	select @Err_msg = isnull(error_message(), 'has not been retrieved'), @Err_svrt = error_severity();
	if @@trancount > 0 rollback;
	raiserror (@Err_msg, @Err_svrt, 1) with nowait;
end catch;

--#endregion
