/*
Autogenerated by excavator tool, version 1.0.0.0
__GENERATED_TIMESTAMP__
Source: 129.212.168.210,1433
Database: budzdorov_Core
*/
use budzdorov_Core


GO
set nocount on
go
set ansi_nulls on
go
set quoted_identifier on
go

begin try
begin tran
	--#region Payments
		declare @PaymentsUnIdUn2488889 int

		if not exists(select * from Payments where [Id] = 2488889 )
		begin
		insert into Payments ([PaymentDate],[WithCreditCard],[AcceptOffice_Id],[CashierAccepted_Id],[Method],[Sum],[PatientAccount_Id],[CenterId])
		values (02.06.2021 0:00:00 +05:00,0,13,9599,0,802.0000,1642107,9)
		set @PaymentsUnIdUn2488889 = SCOPE_IDENTITY()

		end
	else
		begin
			update Payments
			set [PaymentDate] = 02.06.2021 0:00:00 +05:00 , [WithCreditCard] = 0 , [AcceptOffice_Id] = 13 , [CashierAccepted_Id] = 9599 , [Method] = 0 , [Sum] = 802.0000 , [PatientAccount_Id] = 1642107 , [CenterId] = 9
			where [Id] = 2488889
			select @PaymentsUnIdUn2488889 = Id
			from Payments
			where [Id] = 2488889
		end

	--#endregion Payments

rollback

end try
--#region catch
begin catch
	declare @Err_msg nvarchar(2048), @Err_svrt int
	select @Err_msg = isnull(error_message(), 'has not been retrieved'), @Err_svrt = error_severity();
	if @@trancount > 0 rollback;
	raiserror (@Err_msg, @Err_svrt, 1) with nowait;
end catch;

--#endregion
