/*
Autogenerated by excavator tool, version 1.0.0.0
__GENERATED_TIMESTAMP__
Source: 129.212.168.210,1433
Database: budzdorov_Core
*/
use budzdorov_Core


GO
set nocount on
go
set ansi_nulls on
go
set quoted_identifier on
go

begin try
begin tran
	--#region Employees
		declare @EmployeesUnIdUn1 int

		if not exists(select * from Employees where [Id] = 1 )
		begin
		insert into Employees ([Center_Id],[FIO],[Login],[CreationTime],[PhoneNumber],[IsActive],[EntityVersion],[IsCashObserver],[PersonnelNumber],[DCode])
		values (1,N'SuperAdmin (Не трогать)',N'SuperAdmin',31.05.2021 20:37:31 +03:00,N'1',0,6,1,1,1)
		set @EmployeesUnIdUn1 = SCOPE_IDENTITY()

		end
	else
		begin
			update Employees
			set [Center_Id] = 1 , [FIO] = N'SuperAdmin (Не трогать)' , [Login] = N'SuperAdmin' , [CreationTime] = 31.05.2021 20:37:31 +03:00 , [PhoneNumber] = N'1' , [IsActive] = 0 , [EntityVersion] = 6 , [IsCashObserver] = 1 , [PersonnelNumber] = 1 , [DCode] = 1
			where [Id] = 1
			select @EmployeesUnIdUn1 = Id
			from Employees
			where [Id] = 1
		end

	--#endregion Employees

rollback

end try
--#region catch
begin catch
	declare @Err_msg nvarchar(2048), @Err_svrt int
	select @Err_msg = isnull(error_message(), 'has not been retrieved'), @Err_svrt = error_severity();
	if @@trancount > 0 rollback;
	raiserror (@Err_msg, @Err_svrt, 1) with nowait;
end catch;

--#endregion
