/*
Autogenerated by excavator tool, version 1.0.0.0
__GENERATED_TIMESTAMP__
Source: 129.212.168.210,1433
Database: budzdorov_Core
*/
use budzdorov_Core


GO
set nocount on
go
set ansi_nulls on
go
set quoted_identifier on
go

begin try
begin tran
	--#region TherapyPrograms
		declare @TherapyProgramsUnIdUn904 int

		if not exists(select * from TherapyPrograms where [Id] = 904 )
		begin
		insert into TherapyPrograms ([Patient_Id],[State],[CreatorDoctor_Id],[SigningTime],[Diagnosis_Id],[DiagnosisKind],[PaymentMethod],[Credit],[TotalCost],[LastProvidedServiceTime],[AssignedInCenterId],[AttachedDoctor_Id],[HasServicesByInsurance],[AttachedDoctorCenterId])
		values (1642107,3,9916,09.06.2021 10:19:10 +03:00,6053,0,0,0.0000,2190,09.06.2021 11:13:20 +00:00,17,9916,0,17)
		set @TherapyProgramsUnIdUn904 = SCOPE_IDENTITY()

		end
	else
		begin
			update TherapyPrograms
			set [Patient_Id] = 1642107 , [State] = 3 , [CreatorDoctor_Id] = 9916 , [SigningTime] = 09.06.2021 10:19:10 +03:00 , [Diagnosis_Id] = 6053 , [DiagnosisKind] = 0 , [PaymentMethod] = 0 , [Credit] = 0.0000 , [TotalCost] = 2190 , [LastProvidedServiceTime] = 09.06.2021 11:13:20 +00:00 , [AssignedInCenterId] = 17 , [AttachedDoctor_Id] = 9916 , [HasServicesByInsurance] = 0 , [AttachedDoctorCenterId] = 17
			where [Id] = 904
			select @TherapyProgramsUnIdUn904 = Id
			from TherapyPrograms
			where [Id] = 904
		end

		declare @TherapyProgramItemsUnIdUn1039 int

		insert into TherapyProgramItems ([MedicalService_Id],[IsCanceled],[DiscountValue],[DiscountPercent],[DiscountedPrice],[ServicesCount],[ProvidedServicesCount],[Program_Id],[ServicesCanBeCancelled],[ServicesCanBeAdded],[PaymentMethod],[AllServicesCost_Price],[AllServicesCost_DiscountPercents],[AllServicesCost_DiscountValue],[AllProvidedServicesCost_Price],[AllProvidedServicesCost_DiscountPercents],[AllProvidedServicesCost_DiscountValue])
		values (6793,0,0.0000,0,1690.0000,1,1,@TherapyProgramsUnIdUn904,1,1,0,1690.0000,0,0.0000,1690.0000,0,0.0000)
		set @TherapyProgramItemsUnIdUn1039 = SCOPE_IDENTITY()


		declare @TherapyProgramItemsUnIdUn1047 int

		insert into TherapyProgramItems ([MedicalService_Id],[IsCanceled],[DiscountValue],[DiscountPercent],[DiscountedPrice],[ServicesCount],[ProvidedServicesCount],[Program_Id],[ServicesCanBeCancelled],[ServicesCanBeAdded],[PaymentMethod],[AllServicesCost_Price],[AllServicesCost_DiscountPercents],[AllServicesCost_DiscountValue],[AllProvidedServicesCost_Price],[AllProvidedServicesCost_DiscountPercents],[AllProvidedServicesCost_DiscountValue])
		values (359,0,0.0000,0,500.0000,1,1,@TherapyProgramsUnIdUn904,1,1,0,500.0000,0,0.0000,500.0000,0,0.0000)
		set @TherapyProgramItemsUnIdUn1047 = SCOPE_IDENTITY()


	--#endregion TherapyPrograms

rollback

end try
--#region catch
begin catch
	declare @Err_msg nvarchar(2048), @Err_svrt int
	select @Err_msg = isnull(error_message(), 'has not been retrieved'), @Err_svrt = error_severity();
	if @@trancount > 0 rollback;
	raiserror (@Err_msg, @Err_svrt, 1) with nowait;
end catch;

--#endregion
